name: Publish to Maven Central

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn -B -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" \
          -DskipTests \
          -Dossrh.username="${{ secrets.OSSRH_USERNAME }}" \
          -Dossrh.password="${{ secrets.OSSRH_PASSWORD }}" \
          -P release \
          clean deploy